### PR TITLE
Remove all radio stations but aqua and aqua lofi

### PR DESCRIPTION
**Pull request by HexDevv**
lets be real, they're all trash

### CODE REVIEW

**Comment by DamonOnYT** [comment]
i approve of this change

**Comment by Maxisthemoose** [comment]
e

**Comment by Maxisthemoose** [comment]
e

**Comment by Maxisthemoose** [comment]
This is my new way of communicating through chat

**Comment by Maxisthemoose** [comment]
Help me please

**Comment by Lachie-Source** [comment]
good idea

**Comment by HexDevv** [comment]
yo Prox there's like 4 people who have approved this change my guy lmfao

**Comment by HexDevv** [comment]
Closing due to the reason that prox won't fucking accept this, and I need to work on smth

**Pull request closed without merging**
