### PR TITLE
Pulse Web

### PR DESCRIPTION
**Pull request by Lachie-Source**
it's a short one, but imma add some radios and stuff

### CODE REVIEW

**Comment by DefectivenessYT** [comment]
prox, wouldnt reccomend accepting any of this guys pr’s, he made a bot called eval, the profile pic could be changed, the token exposed, and the responses were not sanitised at all.

**Comment by HexDevv** [comment]
gonna have to +1 @DefectivenessYT

**Comment by Lachie-Source** [comment]
@DefectivenessYT am big dumb and didn't know client.token was a thing lmfao.

**Comment by Lachie-Source** [comment]
also how tf did u know i was bumpy

**Comment by DamonOnYT** [comment]
@Lachie-Source ur broken eval bot linked to a github repo lol

**Comment by HexDevv** [comment]
@Lachie-Source we had the ability to wipe wherever your bot was hosted at the time. how come you didn't blacklist rm?

**Comment by DefectivenessYT** [comment]
client.token wasn't the only thing you've been dumb about, we could have deleted your host machine!

**Pull request closed without merging**
